visualization/visualization_utils.py, visualization/visualize_detector_output.py, visualization/visualize_incoming_annotations.py
=> Script to visualize a sample of incoming annotations

data_management/databases/sanity_check_json_db.py, data_management/importers/missouri_to_json.py, visualization/visualize_bbox_db.py
minor updates in sanity_check_json_db and visualize_bbox_db
=> Prepared Missouri Camera Traps data set for LILA

api/batch_processing/find_problematic_detections.py, data_management/annotations/add_bounding_boxes_to_json.py, data_management/databases/analyze_json_database.py, data_management/databases/remove_corrupted_images_from_database.py, data_management/databases/sanity_check_json_db.py, data_management/tfrecords/classification/create_tfrecords_from_coco.py, data_management/tfrecords/tools/inspect_tfrecords_batch.py, demo/run_tf_detector.py, detection/run_tf_detector.py, requirements.txt, visualization/visualize_db.py, visualization/visualize_incoming_annotations.py
- Add `requirements.txt` for scripts outside of `classification`, `demo` and `detection`.
- Regroup import statements and delete unused import statements.
- Minor minor format change to `find_problematic_detections.py`
=> Add requirements.txt 

api/batch_processing/postprocess_batch_results.py, detection/run_tf_detector_batch.py
Added a new script - run_tf_detector_batch.py - that invokes our model serially on a single node, but produces output in the same format as the batch processing API.  Technically it's one output format version behind the API, but we're getting there.
=> Tf detector batch

classification/api/api_apply_classifier_single_node.py
Changes in classification/api/api_apply_classifier_single_node.py:
- Changed float output to use flooring with 3 significant digits
- Changed indent to 1
=> Changed output format of classifier json inference

api/batch_processing/README.md
Added the links to api/batch_processing/README.md
=> Added links to samples for API classifier and post-processing output

classification/TUTORIAL.md, data_management/databases/classification/convert_json_detections_to_pickle.py
- Fixed typo in classification tutorial
- Added script for converting API JSON output to pickle file
=> Tutorial typo + new conversion script

api/batch_processing/postprocessing/convert_output_format.py, detection/run_tf_detector_batch.py
Temporary fix before the async, sync and offline inference functions get refactored. 
Address issue reported by AWC.
=> Make batch inference script consistent with Async API results

api/batch_processing/postprocessing/postprocess_batch_results.py, ct_utils.py, data_management/annotations/annotation_constants.py, detection/run_tf_detector.py, detection/run_tf_detector_batch.py, environment-detector.yml, visualization/visualization_utils.py, visualization/visualize_detector_output.py
run_tf_detector.py no longer self-contained. Visualization utility functions moved back to visualization_utils.py
=> Refactor inference functions (round 2)

data_management/megadb/converters/cct_to_megadb.py, data_management/megadb/importer_notebooks/megadb_add_ena24.ipynb
Updated the script for handling bbox and duplicate class names issues.
Added notebook for ena24 dataset.
=> Ena24 megadb

detection/run_tf_detector.py, visualization/visualization_utils.py
Detected objects are cropped and saved in out_dr.
For multiple objects in a single image, a numerical prefix is used for each object.
=> Cropping and Saving functionality added for run_tf_detector.py

api/synchronous/README.md, api/synchronous/api_core/build_docker.sh, data_management/annotations/annotation_constants.py, detection/run_tf_detector.py, visualization/visualization_utils.py
- Tidy up sync API.
- Fix wrong int label for vehicle class in detection inference scripts.
=> Fix wrong int label for vehicle class in inference scripts

api/synchronous/api_core/Dockerfile, api/synchronous/api_core/supervisord.conf, api/synchronous/synchronous_api_test.py
Change the number of workers and therefore number of API instances running and models loaded to 1 for prod version of Docker image.
=> Change number of workers to 1 for sync API

detection/README.md, detection/run_tf_detector.py, detection/run_tf_detector_batch.py, megadetector.md
- improved documentation in and cleaned up Markdown files
- removed duplicate code in run_tf_detector_batch.py
- improved documentation in run_tf_detector.py
- inching towards PEP8 style compatibility
=> Update documentation for run_tf_detector*.py to use MegaDetector v4

taxonomy_mapping/process_species_by_dataset.py, taxonomy_mapping/species_lookup.py
Make sure that taxonomy_level and scientific_name columns match the 1st entry in taxonomy_string
=> manual taxonomy mapping: add printouts for manual checks

visualization/visualize_detector_output.py
To be compatible with: https://github.com/microsoft/ai4eutils/pull/14
=> update visualize_detector_output.py to new sas_blob_utils.py

api/synchronous/example/locustfile.py
updated locustfile to use latest locust api (for latest version of locust, version 1.1.1)
=> updated locustfile to use latest locust api

data_management/importers/helena_to_cct.py, data_management/importers/island_conservation_to_json.py, data_management/importers/save_the_elephants_survey_B.py, data_management/megadb/converters/cct_to_megadb.py, data_management/megadb/importer_notebooks/megadb_add_ena24.ipynb, data_management/megadb/importer_notebooks/megadb_add_island_conservation.ipynb, data_management/megadb/importer_notebooks/megadb_add_rspb.ipynb, data_management/megadb/importer_notebooks/megadb_add_ste_survey_a.ipynb, data_management/megadb/importer_notebooks/megadb_add_ste_survey_b.ipynb
Scripts to create CCT JSON files for Island Conservation and RSPB datasets
Scripts to create MegaDB JSON files for CCT JSON for STE, RSPB and Island Conservation.
@Siyu - I've updated cct_to_megadb,py file to handle if few annotations doesn't have bbox to avoid the error for island conservation dataset.
=> Helena detections

detection/megadetector_colab.ipynb
Issue reported by Snigdha Saha.
=> Rewrite TFv1 installation instructions for Colab

detection/detector_eval/detector_eval.py, detection/detector_eval/mdv4_1_calibration.ipynb
Code to plot calibration curves for MegaDetector v4.1.
Runs isotonic regression for calibration, and saves calibration function that can be reloaded later.
=> MDv4.1 calibration

data_management/megadb/download_images.py
download script now supports both MegaDB query outputs and Batch Detection API output files
=> updated images download script

api/batch_processing/README.md, api/batch_processing/data_preparation/manage_api_submission.md, api/batch_processing/data_preparation/manage_api_submission.py, api/batch_processing/data_preparation/prepare_api_submission.py, api/batch_processing/postprocessing/combine_api_outputs.py, data_management/megadb/megadb_utils.py, environment-api-task-management.yml
Main changes:
1) I made the naming consistent by replacing every instance of "job" with "task"
2) I wrote a new "Task" class which encapsulates the most common things we do with a task (e.g., uploading its image list, generating API request, submitting the API request, checking the status, and getting missing images for resubmission)
3) I refactored the code to use functions from the ai4eutils repo wherever possible
4) Programmatic API submission now works and does not require Postman. Of course, using Postman is still possible.
=> Refactor Batch API Submission Code

classification/README.md, classification/create_classification_dataset.py, classification/crop_detections.py
updated files in classification/ directory:
create_classification_dataset.py
crop_detections.py
README.md
=> classification: use --threshold instead of --confidence-threshold

classification/README.md, classification/json_validator.py, taxonomy_mapping/taxonomy_csv_checker.py, taxonomy_mapping/taxonomy_graph.py
**`classification/json_validator.py`**
- merge parse_taxa() into parse_spec()
- fix minor typo
**`classification/README.md`**
- fix errors in example classification label specification JSON
**`taxonomy_mapping/taxonomy_csv_checker.py`**
- checks if ambiguous parents have hard-coded resolution in taxonomy_graph.dag_to_tree()
- clarify comments
**`taxonomy_mapping/taxonomy_graph.py`**
- clarify comments
=> Taxonomy-related improvements

api/batch_processing/integration/digiKam/setup.py, api/batch_processing/integration/digiKam/xmp_integration.py
added optional arguments and UI for number of threads and rename files based on input parameters
=> Added optional arguments for threads and renaming image names

api/synchronous/example/README.md, api/synchronous/example/node_example/.gitignore, api/synchronous/example/node_example/config.js, api/synchronous/example/node_example/main.js, api/synchronous/example/node_example/package-lock.json, api/synchronous/example/node_example/package.json
Added some sample code in `api/synchronous/example/`to invoke the synchronous Megadetector API using Node. I had  trouble getting the multipart form to work with [Axios](https://github.com/axios/axios), but I had success with [Superagent](https://visionmedia.github.io/superagent/), so I thought providing a working example might be useful to anyone who's trying to do the same.
Thanks for considering this PR!
=> Add sample API invocation script with node/js

classification/README.md, classification/create_classification_dataset.py
Fix bug in create_classification_dataset.py where `test_frac` argument was handled incorrectly.
=> Classification fixes

classification/train_utils.py
Previously, if `label_weighted=True`, then all examples within the same label were given the same weight, even if `weight_by_detection_conf` was given or True. The weighting scheme is now corrected so that `label_weighted=True` still gives each label equal weight, but examples within a label are now weighted proportional to their detection confidence.
=> Fix classification weights

README.md, classification/README.md, classification/aggregate_classifier_probs.py, classification/analyze_failed_images.py, classification/cache_batchapi_outputs.py, classification/create_classification_dataset.py, classification/crop_detections.py, classification/csv_to_json.py, classification/detect_and_crop.py, classification/evaluate_model.py, classification/identify_mislabeled_candidates.py, classification/json_validator.py, classification/map_classification_categories.py, classification/merge_classification_detection_output.py, classification/run_classifier.py, classification/train_classifier.py, classification/train_classifier_tf.py, classification/train_utils.py
Use more intuitive typing annotations from the `__future__` module.
=> Use "future" typing annotations for classification code

api/batch_processing/postprocessing/convert_output_format.py
Make sure the CSV conversion can handle failures in the json data
=> Handle failed detections

megadetector.md
Reference the v1 compat in the readme
=> Updating getting started

visualization/visualize_detector_output.py
A new argument to avoid copying images under a certain confidence threshold
=> not_copy_undetected new argument

taxonomy_mapping/preview_lila_taxonomy.py
=> Fix typo in lila taxonomy preview

detection/run_detector.py
These codes do the same thing as  detector = load_detector(model_file)
=> Remove duplicate codes

README.md
Reverts microsoft/CameraTraps#367
=> Revert "Main branch push test"

README.md
Reverts microsoft/CameraTraps#370
=> Revert "Revert "Main branch push test""

README.md
Reverts microsoft/CameraTraps#375
=> Revert "Code roll back"

INSTALLATION.md, demo/gradio_demo.py, demo/image_demo.py, demo/image_detection_demo.ipynb, demo/video_demo.py, demo/video_detection_demo.ipynb
Added comments for Windows users.
=> Documentation updates for v1.0.0

.gitignore, INSTALLATION.md, PytorchWildlife/data/datasets.py, PytorchWildlife/data/transforms.py, PytorchWildlife/models/detection/yolov5/base_detector.py, PytorchWildlife/utils/post_process.py, demo/gradio_demo.py, setup.py
Fixed batch processing memory leak.
Adjusted documentation.
Changed default Gradio Image type to PIL Image.
=> PyTorchWildlife 1.0.1

README.md, archive/api/batch_processing/api_core/README.md, demo/gradio_demo.py
Fixed an issue where windows users were unable to perform batch detection on the Gradio demo.
Adjusted archive documentation.
=> Pytorch-wildlife v.1.0.2.1

archive/api/batch_processing/api_core/README.md, demo/gradio_demo.py
Fixed a bug where Windows users could not use the Gradio batch processing due to a path error.
Modified a README in the archive.
=> Pytorch-Wildlife v1.0.2.1

.gitignore, PytorchWildlife/utils/post_process.py, archive/api/batch_processing/api_core/server_api_config.py, archive/api/batch_processing/api_core/start_batch_api.sh, demo/image_demo.py, demo/image_detection_demo.ipynb, demo/video_demo.py, demo/video_detection_demo.ipynb, setup.py
- Adjusted the paths from utility functions and demos to make it Windows compatible
- Re-organized some archive files
=> Pytorch-Wildlife v1.0.2.2

PytorchWildlife/__init__.py
Fixed setup bug associated with the Readme
Updated Huggingface spaces link
=> PytorchWildlifev1.0.2.5

README.md, megadetector.md
Added DockerFile for ease of installation
Added instructions on how to use Docker
Added instructions on how to use Jupyter
=> PytorchWildlifev1.0.2.6

README.md
Updated Highlights on readme to show the links to the folder separation demo.
=> Update Highlights update!

PytorchWildlife/utils/post_process.py, demo/image_separation_demo.ipynb, demo/image_separation_demo.py
Modified folder separation function name.
=> Modified folder separation function name

PytorchWildlife/utils/post_process.py, README.md, demo/image_separation_demo.ipynb, demo/image_separation_demo.py
Modified the name of the folder separation function.
=> Pre release
